like/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('like_change', views.like_state_change, name='likechange'),
]

myblog/urls.py
from django.urls import path
from . import views

app_name = 'myblog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_id>', views.blog_detail, name='blog_detail'),
    path(
        'type/<int:blogs_with_type>',
        views.blogs_with_type,
        name='blog_with_type'),
    path(
        'date/<int:year>/<int:month>',
        views.blogs_by_date,
        name='blogs_by_date'),
]

myblog/models.py
from django.db import models
from django.core.cache import cache
from django.contrib.auth.models import User
from django.core.cache.utils import make_template_fragment_key
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor_uploader.fields import RichTextUploadingField
from reading_statistics.models import ReadDetail


# Create your models here.
class BlogType(models.Model):
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return self.type_name


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='标题')
    blog_type = models.ForeignKey(
        BlogType, on_delete=models.CASCADE, verbose_name='博客类型')
    content = RichTextUploadingField(verbose_name='博客内容')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='作者')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    last_modified_time = models.DateTimeField(
        auto_now=True, verbose_name='上次修改时间')
    read_details = GenericRelation(ReadDetail)
    # Show or not
    is_visable = models.BooleanField(default=True, verbose_name='是否可见')

    def __str__(self):
        return '<Blog: %s>' % self.title

    class Meta:
        ordering = ['-create_time']

    # Delete cache when update blog.
    def save(self, *args, **kwargs):
        cache.delete(make_template_fragment_key('blog_content', [self.pk]))
        super().save(*args, **kwargs)

myblog/views.py
from django.conf import settings
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from django.shortcuts import get_object_or_404, render
from .models import Blog, BlogType
from reading_statistics.utils import read_statistics_once

# Create your views here.


def get_blog_list_common(request, blogs):
    # 得到博客的所有类型，用于生成类型边栏
    blog_types = BlogType.objects.all()
    # 分页机制的实现
    page_num = request.GET.get('page', 1)
    paginator = Paginator(blogs, settings.BLOGS_NUM_PER_PAGE)
    blog_page = paginator.get_page(page_num)
    current_page_num = blog_page.number
    page_range = [
        x for x in range(
            max(current_page_num - 2, 1),
            min(current_page_num + 2, paginator.num_pages) + 1)
    ]
    # 加上省略标记
    if page_range[0] > 2:
        page_range.insert(0, '...')
    if paginator.num_pages - page_range[-1] > 1:
        page_range.append('...')
    # 添加首页和尾夜
    if 1 not in page_range:
        page_range.insert(0, 1)
    if paginator.num_pages not in page_range:
        page_range.append(paginator.num_pages)
    # 用于返回的内容
    return {
        'blog_types': blog_types,
        'page_of_blogs': blog_page,
        'page_range': page_range,
        # 生成日期分类边栏
        'blog_dates': Blog.objects.dates('create_time', 'month', order='DESC')
    }


@cache_page(60 * 5)
def blog_list(request):
    blogs = Blog.objects.filter(
        is_visable=True)  # 使用 get_list_or_404 没有博客时返回404,无法显示
    return render(request, 'myblog/blog_list.html',
                  get_blog_list_common(request, blogs))


def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id, is_visable=True)
    cookie_key = read_statistics_once(request, blog)
    previos_blog = Blog.objects.filter(
        create_time__gt=blog.create_time, is_visable=True).last()
    next_blog = Blog.objects.filter(
        create_time__lt=blog.create_time, is_visable=True).first()
    context = {
        'user': request.user,
        'blog': blog,
        'previous_blog': previos_blog,
        'next_blog': next_blog,
    }
    response = render(request, 'myblog/blog_detail.html', context)
    response.set_cookie(cookie_key, 'true')
    return response


@cache_page(60 * 5)
def blogs_with_type(request, blogs_with_type):
    blog_type = get_object_or_404(BlogType, pk=blogs_with_type)
    blogs = Blog.objects.filter(blog_type__pk=blog_type.pk)
    context = {
        'blog_this_type': blog_type,
    }
    context.update(get_blog_list_common(request, blogs))
    return render(request, 'myblog/blog_with_type.html', context)


@cache_page(60 * 5)
def blogs_by_date(request, year, month):
    blogs = Blog.objects.filter(
        create_time__year=year, create_time__month=month)
    context = {
        'blog_this_date': '%d年%d月' % (year, month),
    }
    context.update(get_blog_list_common(request, blogs))
    return render(request, 'myblog/blog_by_date.html', context)

myblog/templates/myblog/blog_by_date.html
{% extends 'myblog/blog_list.html' %}
{% block title %} {{blog_this_date}} {% endblock title %}

{% block blog_card_header %}{{blog_this_date}}{% endblock blog_card_header %}

myblog/templates/myblog/blog_detail.html
{% extends 'blog_base.html' %}

{% load cache %}
{% load static %}
{% load comment_extras %}
{% load reading_statics_extras %}
{% load like_extras %}

{% block title %} {{blog.title}} {% endblock title %}
{% block nav_blog_active %}active{% endblock nav_blog_active %}

{% block header_extends %}
<link rel="stylesheet" href="{% static "myblog/css/blog.css" %}">
<link rel="stylesheet" href="https://at.alicdn.com/t/font_1043352_kbrqyvllufh.css">
<script src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock header_extends %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h3>{{blog.title}}</h3>
            <ul class="blog-info-description">
                <li>作者: {{blog.author}}</li>
                <li>分类: <a href="{% url 'myblog:blog_with_type' blog.blog_type.id %}">{{blog.blog_type}}</a></li>
                <li>发表时间: {{blog.create_time|date:"Y-m-d H:i:s"}}</li>
                <li>阅读:({% get_read_num blog %})</li>
                <li>评论: {% get_comments_count blog %}</li>
            </ul>
            {% cache 172800 blog_content blog.pk %}
                <div class="blog-content">{{blog.content|safe}}</div>
            {% endcache %}
            {% url 'likechange' as url %}
            <div class="like-area" onclick="javascript:like_it(this, '{% get_content_type blog %}', {{blog.pk}}, '{{url}}')">
                <i class="iconfont icon-xihuan1 {% get_likes_states blog %}"></i>
                <span id="likes_num">{% get_likes_count blog %}</span>
                <span>喜欢</span>
            </div>
            <div class="blog-more">
                <p>
                    上一篇:
                    {% if previous_blog %}
                        <a href="{% url 'myblog:blog_detail' previous_blog.pk %}">{{previous_blog.title}}</a>
                    {% else %}
                        没有了
                    {% endif %}
                </p>
                下一篇:
                {% if next_blog %}
                    <a href="{% url 'myblog:blog_detail' next_blog.pk %}">{{next_blog.title}}</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <!-- justify-content-md-center -->
        <div class="col">
            <!-- -md-auto -->
            <div class="comment-area">
                <h3 class="comment-area-title">提交评论</h3>
                <!-- 提交评论区域 -->
                {% if user.is_authenticated %}
                    <!-- 提交评论部分 -->
                    <form action="{% url 'comment' %}" method="post" id="comment-form">
                        {% csrf_token %}
                        <label>欢迎 {{user.get_nickname_or_username}} ,写点什么吧</label>
                        <!-- 多重回复的实现部分 -->
                        <div id="reply_container" style="display: none;">
                            <p id="reply_title">回复: </p>
                            <div id="reply_content"></div>
                        </div>
                        {% get_comments_form blog as comments_form %}
                        {% for field in comments_form %}
                            <div class="form-group">
                                {{field}}
                            </div>
                        {% endfor %}
                        <div class="form-group">
                            <span id="comment_errors" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">提交评论</button>
                        </div>
                    </form>
                {% else %}
                    <a href="{% url 'login' %}?from={{request.get_full_path}}" class="btn btn-primary">登陆</a>
                    <span> or </span>
                    <a href="{% url 'register' %}?from={{request.get_full_path}}" class="btn btn-secondary">注册</a>
                {% endif %}
                <!-- 区域完 -->
            </div>
            <div class="comment-area">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">评论列表</h5>
                    </div>
                    <ul class="list-group list-group-flush" id="comment-box">
                        <!-- 顶层评论列表 -->
                        {% get_comments_list blog as comments_list %}
                        {% for comment in comments_list %}
                            <li class="list-group-item">
                                <small>
                                    <span>{{comment.author.get_nickname_or_username}}</span>
                                    <span>{{comment.comment_time|date:"Y-m-d G:i:s"}}</span>
                                </small>
                                <br>
                                <div id="comment_{{comment.pk}}">
                                    {{comment.comment|safe}}
                                </div>
                                <!-- 点赞 -->
                                <div class="like-area" onclick="javascript:like_it(this, '{% get_content_type comment %}', {{comment.pk}}, '{{url}}')">
                                    <i class="iconfont icon-xihuan1 {% get_likes_states comment %}"></i>
                                    <span id="likes_num">{% get_likes_count comment %}</span>
                                </div>
                                <!-- 跟踪被回复的对象 -->
                                <a href="javascript:reply({{comment.pk}})">回复</a>
                        <!-- 完 -->
                                <!-- 回复楼层 -->
                                <div id="root_{{comment.pk}}">
                                    {% for reply in comment.root_comment.all %}
                                        <div class="reply">
                                            <small>
                                                <span>{{reply.author.get_nickname_or_username}}</span>
                                                <span>{{reply.comment_time|date:"Y-m-d G:i:s"}}</span> 
                                                <span>回复</span>
                                                <span>{{reply.reply_to.get_nickname_or_username}}</span>
                                            </small>
                                            <div id="comment_{{reply.pk}}">
                                                {{reply.comment|safe}}
                                            </div>
                                            <!-- 点赞 -->
                                            <div class="like-area" onclick="javascript:like_it(this, '{% get_content_type reply %}', {{reply.pk}}, '{{url}}')">
                                                <i class="iconfont icon-xihuan1 {% get_likes_states reply %}"></i>
                                                <span id="likes_num">{% get_likes_count reply %}</span>
                                            </div>
                                            <!-- 跟踪被回复的对象 -->
                                            <a href="javascript:reply({{reply.pk}})">回复</a>
                                        </div>
                                    {% endfor %}
                                </div>
                            </li>
                        {% empty %}
                            <div id="no-commend">
                                <li class="list-group-item">暂无评论</li>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock content %}

{% block extra_scripts %}
    <script>
        window.onunload = function(){
            console.log('flash it!');
            {% if user.is_authenticated %}
                $('#reply_to_id').val('0');
                CKEDITOR.instances['id_comment_text'].setData('');
                // 有何作用？？
                CKEDITOR.instances['id_comment_text'].updateElement();
            {% endif %}
        }
    </script>

    <script src="{% static 'myblog/js/blog_detail.js' %}"></script>
{% endblock extra_scripts %}

myblog/templates/myblog/blog_list.html
{% extends 'blog_base.html' %}

{% load static %}
{% load comment_extras %}

{% block title %}
    My Website
{% endblock title %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'myblog/css/blog.css' %}">
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_1043352_kbrqyvllufh.css">
{% endblock header_extends %}

{% block nav_blog_active %}active{% endblock nav_blog_active %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-8 col-lg-9">
                <div class="blog_list_card">
                    <div class="card">
                    <div class="card-body">
                    <div class="card-title">{% block blog_card_header %} 博客列表 {% endblock blog_card_header %}</div>
                        <ul class="list-group list-group-flush">
                            {% for blog in page_of_blogs.object_list %}
                                <li class="list-group-item">
                                    <a href="{% url 'myblog:blog_detail' blog.pk %}"><h3>{{blog.title}}</h3></a>
                                    <div class="blog-info">
                                        <i class="iconfont icon-pricetags">{{blog.blog_type}}</i>
                                        <i class="iconfont icon-clock">{{blog.create_time|date:"Y-m-d"}}</i>
                                        <i class="iconfont icon-pinglun">{% get_comments_count blog %}</i>
                                    </div>
                                    <p>{{blog.content|striptags|truncatechars:60|safe}}</p>
                                </li>
                            {% empty %}
                                <p>暂无博客，敬请期待</p>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                </div>
                <nav aria-label="Page navigation" class="paginator">
                <ul class="pagination">
                    {% if page_of_blogs.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{page_of_blogs.previous_page_number}}">Previous</a></li>
                    {% else %}
                        <li class="page-item disabled"><a href="#" class="page-link">Previous</a></li>
                    {% endif %}
                    {% for page_num in page_range %}
                        {% if page_num == page_of_blogs.number %}
                            <li class="page-item active"><a class="page-link" href="#">{{page_num}}</a></li>
                        {% elif page_num == '...' %}
                            <li class="page-item disabled"><a href="" class="page-link">...</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{page_num}}">{{page_num}}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_of_blogs.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{page_of_blogs.next_page_number}}">Next</a></li>
                    {% else %}
                        <li class="page-item disabled"><a href="#" class="page-link">Next</a></li>
                    {% endif %}
                </ul>
                <p>
                    共有{{page_of_blogs.paginator.count}}篇博客,
                    当前第{{page_of_blogs.number}}页,
                    共{{page_of_blogs.paginator.num_pages}}页
                </p>
                </nav>
            </div>
            <div class="d-none d-sm-block d-sm-none d-md-block col-md-4 col-lg-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">博客分类</h5>
                        <h6 class="card-subtitle mb-2 text-muted" style="font-size: 80%">一共有{{blog_types|length}}种类型</h6>
                        <ul class="blog-card-list">
                            {% for blog_type in blog_types %}
                                <li><a href="{% url 'myblog:blog_with_type' blog_type.pk %}"> {{ blog_type.type_name }} </a></li>
                            {% empty %}
                                <p>-- 暂无分类 --</p>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">日期分类</h5>
                        <ul class="blog-card-list">
                            {% for create_time in blog_dates %}
                                <li>
                                    <a href="{% url 'myblog:blogs_by_date' create_time.year create_time.month %}">{{create_time|date:"Y年m月"}}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

myblog/templates/myblog/blog_with_type.html
{% extends 'myblog/blog_list.html' %}
{% block title %}{{blog_this_type.type_name}}{% endblock title %}

{% block blog_card_header %} 
    分类:{{blog_this_type.type_name}}
    (一共有{{page_of_blogs.paginator.count}}篇博客)
    <a href="{% url 'myblog:blog_list' %}">查看全部博客</a>
{% endblock blog_card_header %} 